#
# Primary repos
#
main: "/sdf/group/rubin/repo/main"
main.sasquatch_dev: "/sdf/group/rubin/repo/main/butler+sasquatch_dev.yaml"
embargo: "s3://embargo@rubin-summit-users/butler.yaml"
embargo.sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_readonly: "s3://embargo@rubin-summit-users/butler-nochain-readonly.yaml"
embargo_session: "s3://embargo@rubin-summit-users/butler_session.yaml"
solarsystem_embargo: "/sdf/group/rubin/repo/solarsystem_embargo"
solarsystem: "/sdf/group/rubin/repo/solarsystem"
#
# Release prep and release repos
#
prompt: "/sdf/group/rubin/repo/prompt"
dp1_prep: "/sdf/group/rubin/repo/dp1_prep"
dp1: "/sdf/group/rubin/repo/dp1"
#
# Instrument aliases
#
LATISS: "/sdf/group/rubin/repo/main"
LSSTComCam: "/sdf/group/rubin/repo/main"
LSSTCam: "/sdf/group/rubin/repo/main"
#
# Also useful repos
#
dc2: "/sdf/group/rubin/repo/dc2"
dc2.sasquatch_dev: "/sdf/group/rubin/repo/dc2/butler+sasquatch_dev.yaml"
bts: "s3://rubin-bts-users/butler.yaml"
tts: "s3://rubin-tts-users/butler.yaml"
ir2: "/sdf/group/rubin/repo/ir2"
aos_imsim: "/sdf/group/rubin/repo/aos_imsim"
ucd: "/sdf/group/rubin/repo/ucd"
#
# Deprecated aliases
#
oga: "s3://rubin-summit-users/butler.yaml"
hsc-temp: "/sdf/group/rubin/repo/main_20220411"
ops-rehearsal-3-prep: "/sdf/group/rubin/repo/ops-rehearsal-3-prep"
embargo+sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
"/repo/ops-rehearsal-3-prep": "/sdf/group/rubin/repo/ops-rehearsal-3-prep"
"/repo/ops-rehearsal-3-prep.sasquatch_dev": "/sdf/group/rubin/repo/ops-rehearsal-3-prep/butler+sasquatch_dev.yaml"
"/repo/ops-rehearsal-3-prep+sasquatch_dev": "/sdf/group/rubin/repo/ops-rehearsal-3-prep/butler+sasquatch_dev.yaml"
embargo_or4: "s3://embargo@rubin-summit-users/butler.yaml"
embargo_or4+sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_or4.sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_new: "s3://embargo@rubin-summit-users/butler.yaml"
embargo_new+sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_new.sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
/repo/embargo_new: "s3://embargo@rubin-summit-users/butler.yaml"
/repo/embargo_new+sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
/repo/embargo_new.sasquatch_dev: "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_old: "s3://rubin-summit-users/butler.yaml"
embargo_old.sasquatch_dev: "s3://rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_old+sasquatch_dev: "s3://rubin-summit-users/butler+sasquatch_dev.yaml"
/repo/embargo_old: "s3://rubin-summit-users/butler.yaml"
/repo/embargo_old.sasquatch_dev: "s3://rubin-summit-users/butler+sasquatch_dev.yaml"
/repo/embargo_old+sasquatch_dev: "s3://rubin-summit-users/butler+sasquatch_dev.yaml"
embargo_or5: "s3://embargo@repo-test-users/or5/butler.yaml"
embargo_or5+sasquatch_dev: "s3://embargo@repo-test-users/or5/butler+sasquatch_dev.yaml"
embargo_or5.sasquatch_dev: "s3://embargo@repo-test-users/or5/butler+sasquatch_dev.yaml"
/repo/dp1: "/sdf/group/rubin/repo/dp1"
/repo/dp1_prep: "/sdf/group/rubin/repo/dp1_prep"

"/repo/main": "/sdf/group/rubin/repo/main"
"/repo/main.sasquatch_dev": "/sdf/group/rubin/repo/main/butler+sasquatch_dev.yaml"
"/repo/main+sasquatch_dev": "/sdf/group/rubin/repo/main/butler+sasquatch_dev.yaml"
"/repo/dc2": "/sdf/group/rubin/repo/dc2"
"/repo/dc2+sasquatch_dev": "/sdf/group/rubin/repo/dc2/butler+sasquatch_dev.yaml"
"/repo/embargo": "s3://embargo@rubin-summit-users/butler.yaml"
"/repo/bts": "s3://rubin-bts-users/butler.yaml"
"/repo/tts": "s3://rubin-tts-users/butler.yaml"
"/repo/ir2": "/sdf/group/rubin/repo/ir2"
"/repo/aos_imsim": "/sdf/group/rubin/repo/aos_imsim"
"/repo/ucd": "/sdf/group/rubin/repo/ucd"
"/repo/hsc-temp": "/sdf/group/rubin/repo/main_20220411"
"/repo/oga": "s3://rubin-summit-users/butler.yaml"
"/repo/embargo.sasquatch_dev": "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
"/repo/embargo+sasquatch_dev": "s3://embargo@rubin-summit-users/butler+sasquatch_dev.yaml"
"/repo/prompt": "/sdf/group/rubin/repo/prompt"
