- collection: LSSTCam/prompt/output-2025-04-20
  where: "instrument='LSSTCam' and day_obs=20250420"
  dataset_types: ["deepCoadd", 
                  "deepCoadd_directWarp*",
                  "deepCoadd_psfMatchedWarp*",
                  "objectTable",
                  "sourceTable",
                  "deepCoadd_det*",
                  "deepCoadd_mergeDet*",
                  "deepCoadd_meas*",
                  "deepCoadd_ref*",
                  "deepCoadd_forced_src*",
                  "difference_image_predetection",
                  "goodSeeingDiff_differenceTempExp",
                  "post_isr_image",
                  "postISRCCD",
                  "template_detector",
                  "goodSeeingDiff_templateExp",
                  "template_matched",
                  "goodSeeingDiff_matchedExp",
                  "dia_source_unstandardized",
                  "goodSeeingDiff_candidateDiaSrc",
                  "direct_warp",
                  "psf_matched_warp",
                  "preliminary_visit_image",
                  "preliminary_visit_image_background"]
- collection: LSSTCam/runs/DRP/FL/w_2025_19/DM-50795
  where: "instrument='LSSTCam' and day_obs>=20250415 and day_obs<20250505"
  dataset_types: ["deepCoadd", 
                  "deepCoadd_directWarp*",
                  "deepCoadd_psfMatchedWarp*",
                  "objectTable",
                  "sourceTable",
                  "deepCoadd_det*",
                  "deepCoadd_mergeDet*",
                  "deepCoadd_meas*",
                  "deepCoadd_ref*",
                  "deepCoadd_forced_src*",
                  "difference_image_predetection",
                  "goodSeeingDiff_differenceTempExp",
                  "post_isr_image",
                  "postISRCCD",
                  "template_detector",
                  "goodSeeingDiff_templateExp",
                  "template_matched",
                  "goodSeeingDiff_matchedExp",
                  "dia_source_unstandardized",
                  "goodSeeingDiff_candidateDiaSrc",
                  "direct_warp",
                  "psf_matched_warp",
                  "preliminary_visit_image",
                  "preliminary_visit_image_background"]
  